name: "Deploy to aws"

# Trigger the workflow from the GitHub UI
on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: "Setup node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: npm install 

      - name: "Install pm2 globally"
        run: npm install -g pm2

      # Removed test step (since no test script in package.json)

      - name: "Deploy to aws with pm2"
        run: pm2 start npm -- start
