name: "Deploy to aws"

# Trigger the workflow from the GitHub UI
on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: "Setup node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        run: npm install 

      - name: "Intall pm2 globally"
        run: npm instal pm2 -g

      - name: "Run the tests"
        run: npm test

      - name: "Deploye to aws"
        run : pm2 start/nodemon server.js